services:
  postgres:
    container_name: expense-manager
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: expense-manager
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: expense-manager-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
